---
# tasks file for deploy_services

### Install docker on Debian and RedHat hosts
- block:
    - include_tasks: install_docker_debian.yml
  when: ansible_os_family == "Debian"

- block:
    - include_tasks: install_docker_redhat.yml
  when: ansible_os_family == "RedHat"

- name: "Add insecure registry"
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - Restart Docker

- name: "Login in private docker.registry [192.168.140.136:5000]"
  docker_login:
    registry_url: "{{ registry }}"
    username: "{{ registry_user }}"
    password: "{{ registry_password }}"

- name: "Create directories for RabbitMQ and PostgreSQL volumes"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /rabbitmq/data/
    - /rabbitmq/log/
    - /postgres/data/
    - /postgres/log/

- name: "Copy docker-compose.yml file"
  copy:
    src: docker-compose.yml
    dest: "{{ item }}"
  with_items:
    - ~/docker-compose.yml
    - /home/{{ ansible_user }}/docker-compose.yml

- name: "Run containers"
  shell: "docker compose -f ~/docker-compose.yml up -d"

#- name: "Start services with Docker Compose"
#  community.docker.docker_compose:
#    project_src: ~/docker-compose.yml
#    state: present

- name: "List of running containers"
  shell: "docker compose -f ~/docker-compose.yml ps"
  register: docker_ps_result

- debug:
    var: docker_ps_result.stdout_lines
