---
# tasks file for deploy_services

### Install docker on Debian and RedHat hosts
- block:
    - name: "Update the repository cache And Install ca-certificates, curl [Debian]"
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
        state: latest

    - name: "Create directory for keyrings [Debian]"
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: "Download Docker GPG-key to /etc/apt/keyrings/docker.asc [Debian]"
      uri:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        method: GET
        dest: /etc/apt/keyrings/docker.asc
        follow_redirects: safe

    - name: "Ensure correct permissions for docker.asc [Debian]"
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: "Install Docker [Debian]"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: "Start Docker and enable on boot [Debian]"
      service: name=docker state=started enabled=yes

    - name: "Print Docker status [Debian]"
      shell: "systemctl status docker"
      register: docker_status
      
    - debug:
        var: docker_status.stdout
  when: ansible_os_family == "Debian"

- block:
    - name: "Add the Docker repo [RedHat]"
      get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d
        mode: '0644'
      
    - name: "Install Docker [RedHat]"
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: "Start Docker and enable on boot [RedHat]"
      service: name=docker state=started enabled=yes

    - name: "Print Docker status [RedHat]"
      shell: "systemctl status docker"
      register: docker_status

    - debug:
        var: docker_status.stdout
  when: ansible_os_family == "RedHat"

### Login in private registry on infra-main
- name: "Login in private docker.registry [192.168.140.136:5000]"
  docker_login:
    registry_url: "{{ registry }}"
    username: "{{ registry_user }}"
    password: "{{ registry_password }}"

- name: "Create directories for RabbitMQ and PostgreSQL volumes"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /rabbitmq/data/
    - /rabbitmq/log/
    - /postgres/data/
    - /postgres/log/

### Copy docker-compose.yml file to server
- name: "Copy docker-compose.yml file"
  copy:
    src: docker-compose.yml
    dest: ~

### Run containers
- name: "Run containers"
  shell: "docker compose up -d"

### Docker ps
- name: "List of running containers"
  shell: "docker ps"
  register: docker_ps_result

- debug:
    var: docker_ps_result.stdout
