---
- name: Install Docker, PostgreSQL Container, RabbitMQ Container, Publisher-service, Consumer-service
  hosts: "{{ HOST }}"
  become: yes

  roles:
    - { role: deploy_services, when: ansible_system == 'Linux' }
