- name: Install tcpdump
  gather_facts: No
  hosts: monitoring-server
  vars:
    user_name: ansible
  tasks:
    - ping:

    - name: apt install tcpdump
      apt:
        name: tcpdump
        state: latest
      become: yes
