---
- name: Playbook for variables
  hosts: "{{ HOST }}"
  gather_facts: no
  become: yes

  vars:
    message_hello: Hello
    message_content: Content
    secret: SKDJFA@@_FDW432_4321FDS_FD
    version:
      - v1
      - v2
      - v3
    user:
      user1:
        name: test1
        role: admin
      user2:
        name: test2
        role: user
      user3:
        name: test3
        role: admin

  tasks:

  - name: "Print secret [module: debug, arg: var]"
    debug:
      var: secret

  - name: "Print secret [module: debug, arg: msg]"
    debug:
      msg: "Secret phrase {{ secret }}"

  - name: "Compare vars [module: set_fact]"
    set_fact: test_message="{{ message_hello }} {{ message_content }}"

  - debug:
      var: test_message

  - shell: "uptime"
    register: result

  - debug:
      var: result.stdout_lines

  - debug:
      var: version[0]

  - debug:
      var: user.user3.name

  - name: Print element from dict
    debug:
      msg: "{{ user['user1']['name'] }}"
