---
- name: Playbook for variables
  hosts: all_VMs
  become: yes

  vars:
    message_hello: Hello
    message_content: Content
    secret: SKDJFA@@_FDW432_4321FDS_FD


  tasks:

  - name: "Print secret [module: debug, arg: var]"
    debug:
      var: secret

  - name: "Print secret [module: debug, arg: msg]"
    debug:
      msg: "Secret phrase {{ secret }}"

  - name: "Compare vars [module: set_fact]"
    set_fact: test_message="{{ message_hello }} {{ message_content }}"

  - debug:
      var: test_message

  - shell: "uptime"
    register: result

  - debug:
      var: result

  - debug:
      var: result.stdout
