---
# handlers file for deploy_apache
- name: Restart Apache on Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"

- name: Restart Apache on RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
