---
- name: Install Apache and Upload web page to monitoring-server
  hosts: monitoring_vm
  become: yes

  vars:
    source_file: ./apache_html/index.html
    destination: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy web page
    copy: src={{ source_file }} dest={{ destination }} mode=0555
    notify: Restart Apache

  - name: Start Web Server and enable on boot
    service: name=apache2 state=started enabled=yes


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
