---
- name: Install Apache and Upload web page to monitoring-server
  hosts: all_VMs
  become: yes

  vars:
    source_folder: ./web_example
    destination: /var/www/html

  tasks:
  - name: List controlled servers
    debug:
      var: ansible_os_family

  - block: # =========Debian Block=========

      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: "Start Web Server and enable on boot [Debian]"
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - block: # =========Debian Block=========

      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest

      - name: "Start Web Server and enable on boot [RedHat]"
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - name: Copy web page to Web Server
    copy: src={{ item }} dest={{ destination }} mode=0555
    with_fileglob: "{{ source_folder }}/*"
#    copy: src={{ source_folder }}/{{ item }} dest={{ destination }} mode=0555
#    loop:
#        - "index.html"
#        - "styles.css"
    notify:
        - Restart Apache on Debian
        - Restart Apache on RedHat 


  handlers:
  - name: Restart Apache on Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

  - name: Restart Apache on RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
