---
- name:
  hosts: monitoring-server
  become: yes


  tasks:

  - name: Loop
    debug:
      msg: "Hello {{ item }}"
    loop:
      - "1"
      - "2"
      - "3"

  - name: Loop Until
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2 # sec
    retries: 10 # 3 times (default)
    until: output.stdout.find("ZZZZ") == false

  - name: Print output
    debug:
      var: output.stdout
